"use client";

import { useEffect, useState } from "react";
import { Download, Search, Users } from "lucide-react";
import { AdminPage } from "@/components/admin-page";

type Customer = { id: number; name: string; phone: string | null; purchase_count: number; total_spent: number; pending_credit: number; last_purchase_at: string | null };
type CustomerDashboard = { total_customers: number; total_purchases: number; total_spent: number; pending_credits: number; purchases_today: number; customers: Customer[] };
const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? (process.env.NODE_ENV === "production" ? "https://backend-lemon-five-80.vercel.app/api/v1" : "http://localhost:8001/api/v1");
const money = (value: number) => new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(value);

export default function ClientsPage() {
  const [data, setData] = useState<CustomerDashboard | null>(null);
  const [search, setSearch] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { const token = sessionStorage.getItem("coffee_gosen_access_token"); fetch(`${apiUrl}/customers/summary`, { headers: token ? { Authorization: `Bearer ${token}` } : undefined }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.detail ?? "No fue posible cargar los clientes."); return result as CustomerDashboard; }).then(setData).catch((requestError: Error) => setError(requestError.message)); }, []);
  async function exportCustomer(customer: Customer) { const printWindow = window.open("", "_blank", "width=900,height=700"); if (!printWindow) { setError("Permite las ventanas emergentes para exportar el cliente."); return; } const token = sessionStorage.getItem("coffee_gosen_access_token"); const response = await fetch(`${apiUrl}/customers/${customer.id}/export`, { headers: token ? { Authorization: `Bearer ${token}` } : undefined }); const result = await response.json(); if (!response.ok || result.error) { printWindow.close(); setError(result.error ?? "No fue posible exportar el cliente."); return; } const escapeHtml = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;"); const sales = (result.sales as { sale_number: string; total: string; payment_method: string; created_at: string; items: { product: string; quantity: string; unit_price: string }[] }[]).map((sale) => `<article><h3>${escapeHtml(sale.sale_number)} · ${new Date(sale.created_at).toLocaleString("es-CO")}</h3><p>${escapeHtml(sale.payment_method)} · <strong>${money(Number(sale.total))}</strong></p><ul>${sale.items.map((item) => `<li>${escapeHtml(item.product)} · ${item.quantity} unidad(es) · ${money(Number(item.unit_price))}</li>`).join("")}</ul></article>`).join(""); const credits = (result.credits as { original_amount: string; pending_amount: string; status: string; created_at: string }[]).map((credit) => `<li>${new Date(credit.created_at).toLocaleDateString("es-CO")} · Original: ${money(Number(credit.original_amount))} · Pendiente: ${money(Number(credit.pending_amount))} · ${escapeHtml(credit.status)}</li>`).join(""); printWindow.document.write(`<!doctype html><html lang="es"><head><title>Cliente ${escapeHtml(customer.name)}</title><style>body{font-family:Arial,sans-serif;color:#172033;max-width:850px;margin:40px auto;padding:0 24px}h1{margin-bottom:4px}h2{border-bottom:1px solid #ddd;padding-bottom:8px;margin-top:32px}article{border-bottom:1px solid #eee;padding:12px 0}ul{padding-left:20px;line-height:1.7}.muted{color:#667085}@media print{body{margin:20px auto}}</style></head><body><h1>Reporte de cliente</h1><p class="muted">${escapeHtml(customer.name)}${customer.phone ? ` · ${escapeHtml(customer.phone)}` : ""}</p><h2>Compras</h2>${sales || "<p>No hay compras registradas.</p>"}<h2>Créditos</h2><ul>${credits || "<li>No hay créditos registrados.</li>"}</ul></body></html>`); printWindow.document.close(); printWindow.focus(); printWindow.setTimeout(() => printWindow.print(), 250); }
  const customers = data?.customers.filter((customer) => customer.name.toLowerCase().includes(search.toLowerCase())) ?? [];
  return <AdminPage title="Clientes" description="Consulta compras, cuentas pendientes y exporta el historial completo de cada cliente.">
    {error && <p role="alert" className="border border-red-200 bg-red-50 p-5 text-sm text-red-700">{error}</p>}
    {data && <><div className="grid gap-px border border-[var(--line)] bg-[var(--line)] sm:grid-cols-2 xl:grid-cols-5">{[["Clientes registrados", data.total_customers], ["Compras registradas", data.total_purchases], ["Total gastado", money(data.total_spent)], ["Cuentas pendientes", money(data.pending_credits)], ["Compras hoy", data.purchases_today]].map(([label, value]) => <div key={String(label)} className="bg-white p-5"><p className="text-sm text-[var(--muted)]">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p></div>)}</div><div className="mt-6 border border-[var(--line)] bg-white"><div className="border-b border-[var(--line)] p-4"><label className="relative block"><span className="sr-only">Buscar clientes</span><Search size={18} className="absolute left-3 top-3.5 text-[var(--muted)]" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar cliente" className="min-h-11 w-full border border-[var(--line)] pl-10 pr-4 outline-none focus:border-[var(--blue-main)]" /></label></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="border-b border-[var(--line)] text-[var(--muted)]"><tr><th className="p-4 font-medium">Cliente</th><th className="p-4 font-medium">Compras</th><th className="p-4 font-medium">Total gastado</th><th className="p-4 font-medium">Pendiente</th><th className="p-4 font-medium">Última compra</th><th className="p-4 font-medium">PDF</th></tr></thead><tbody>{customers.map((customer) => <tr key={customer.id} className="border-b border-[var(--line)] last:border-0"><td className="p-4"><strong>{customer.name}</strong>{customer.phone && <span className="mt-1 block text-xs text-[var(--muted)]">{customer.phone}</span>}</td><td className="p-4">{customer.purchase_count}</td><td className="p-4">{money(customer.total_spent)}</td><td className="p-4">{money(customer.pending_credit)}</td><td className="p-4 text-[var(--muted)]">{customer.last_purchase_at ? new Date(customer.last_purchase_at).toLocaleDateString("es-CO") : "Sin compras"}</td><td className="p-4"><button onClick={() => exportCustomer(customer)} title="Exportar cliente a PDF" aria-label={`Exportar ${customer.name} a PDF`} className="grid size-10 place-items-center border border-[var(--line)] text-[var(--blue-main)] hover:bg-[var(--blue-light)]"><Download size={17} /></button></td></tr>)}</tbody></table>{customers.length === 0 && <div className="p-10 text-center text-sm text-[var(--muted)]"><Users className="mx-auto mb-3 text-[var(--blue-main)]" size={26} />No hay clientes registrados.</div>}</div></div></>}
  </AdminPage>;
}
